service: moh-deh-backend-challenge

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221

  stage: api
  region: us-west-2

# you can define service wide environment variables here
  environment:
    ACCESS_TOKEN: ${env:AWS_ACCESS_KEY_ID }
    SECRET_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    TABLE_NAME: Devices

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  app:
    handler: bin/main
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

UsersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: users
    AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
    KeySchema:
      - AttributeName: user_id
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5